### ISSUE TITLE
Option to support unbundled-bezier curves

### ISSUE THREAD

**Issue by petermoore14** [iVis-at-Bilkent/cytoscape.js-edge-editing#13]
The cytoscape.js website advertises that this plugin allows one to work with bezier curves, but from what I can tell it only works with segments at present. Experimented a bit locally and it looks like it won't be too much work to support an option for unbundled-bezier. Will make a PR for this option in the near future unless there are any concerns/objections.

**Comment by ugurdogrusoz** [comment]
@metincansiper what do you think?

**Comment by ugurdogrusoz** [comment]
@petermoore14 Yes, please make a PR for this option.

**Comment by edwinlimlx** [comment]
any update on this? looking forward to creating editable edges with rounded bendpoints

![image](https://user-images.githubusercontent.com/514865/49624058-00cfc200-fa0b-11e8-8b66-f15dff638eb8.png)

**Comment by NoAvailableAlias** [comment]
Looks like petermoore14 got it half completed but has since disappeared. Also it looks like only support for control points was added to unbundled curves so no curvy line segments.

**Comment by ugurdogrusoz** [comment]
Now the user can add *control points* on unbundled Bezier edges.
