### ISSUE TITLE
Rename and release

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-edge-editing#18]
- ~~Make one last patch release of the *master* branch with the current name to publish to npm (ivisatbilkent/usual passwd) with updates to README.  Something like "this package is deprecated in favor of the <new-package-name> package".~~

- ~~Deprecate the old package in npm: https://docs.npmjs.com/cli/deprecate~~

- ~~Rename the repo as "cytoscape.js-edge-editing"~~

In unstable:
- ~~Document the new edge reconnection support in README~~
- ~~Update the "demo" to
    o include the new edge re-connection handles
    o include a bend in one of the edges on load (which was missing previously)~~

These are to be done later (after testing):
- Merge unstable to master

- Release as 2.0.0 in Github

- Release the library in npm as "cytoscape-edge-editing"

- Assign it back to me so I can notify Cytoscape.js guys to update the extension list in their web page

**Comment by hasanbalci** [comment]
I think, in addition to the changes mentioned in "In unstable" part of the above comment, all places where the old extension name passes must be changed with the new one in bower.json, demo.html, gulpfile.js and package.json files. 

This change must also be done in the files exist in src folder, especially in index.js file where we register the extension to Cytoscape.js. 

The name of cytoscape-edge-bend-editing.js file must also be changed correctly and demo.html file must use the file with the new name.

**Comment by ugurdogrusoz** [comment]
Can we make change the layout of the nodes in the demo so that edges don't overlap unrelated nodes?

**Comment by ugurdogrusoz** [comment]
Can we also change wheel sensitivity (make it more refined, slower)?

**Comment by hasanbalci** [comment]
We also need to update the Cytoscape.js dependency as >= 3.0.0, since the edge reconnection feature does not work properly in the previous versions. (Cytoscape.js also wants users to use versions 3.x.x. anyway.)

**Comment by meghansh36** [comment]
When will the new release come out?

**Comment by ugurdogrusoz** [comment]
It is planned for this summer.

**Comment by meghansh36** [comment]
Till then is there any way I can use it in my project?

**Comment by ugurdogrusoz** [comment]
This extension was previously released with a different name on npm: https://www.npmjs.com/package/cytoscape-edge-bend-editing
Feel free to use it until a new version is available.

**Comment by meghansh36** [comment]
Will this be compatible with the newer version of cytoscape?

**Comment by ugurdogrusoz** [comment]
Yes, normally we release with the latest Cytoscape.js version.

**Comment by ugurdogrusoz** [comment]
No need for an issue for this
