### ISSUE TITLE
Updates required in the demo and readme file

### ISSUE THREAD

**Issue by MobiZaman** [iVis-at-Bilkent/cytoscape.js-edge-editing#22]
In the demo file, a parameter "bendRemovalSensitivity" has been mentioned, which is not present anywhere in the cytoscape-edge-editing.js file. This parameter is also mentioned in the readme file.

In the readme file, some other options have also been mentioned which are not actually present in the default options in the code. They have been separately created as variables, such as handleReconnectEdge, validateEdge and actOnUnsuccessfulReconnection.

**Comment by nasimsaleh** [comment]
@MobiZaman "bendRemovalSensitivity"  is an option for edge-editing extension, why would it be mentioned in undo-redo. 
The options that you mentioned (handleReconnectEdge, validateEdge and actOnUnsuccessfulReconnection) are functions which has the default value undefined, they don't need to be initialized in options. It is unnecessary. The readme file correctly reflects the functionality. I think there is no problem here. If you are OK with the reply, please close the issue.

**Comment by MobiZaman** [comment]
The issue is resolved
