### ISSUE TITLE
Self-edge related issue

### ISSUE THREAD

**Issue by PermanAtayev** [iVis-at-Bilkent/cytoscape.js-edge-editing#23]
So if I take an edge from two nodes, and make it a self-edge(source and targets are the same) and if after that I try to insert a bending point to that edge I get errors and the canvas kind of crashes. Because nothing can be manipulated anymore.

![image](https://user-images.githubusercontent.com/38570154/64250193-29470700-cf1e-11e9-812b-ab8eecab03dd.png)

**Comment by nasimsaleh** [comment]
@ugurdogrusoz  Is edge-editing supposed to support self-edge. I didn't implement it, but by checking the code it seems it wont support it. there are calculations of slope at MANY places in the code, and since source and target are same, it ends up dividing by zero giving NaN value.

**Comment by ugurdogrusoz** [comment]
Let's just gracefully ignore editing of self edges.

**Comment by nasimsaleh** [comment]
@PermanAtayev  could please check and close if OK.

**Comment by nasimsaleh** [comment]
@PermanAtayev I forgot to mention that now self-edges and edges with same start and end points are not supported. so you won't be able to add a bend point to the self-edge but you can still use the re-connection handles.

**Comment by PermanAtayev** [comment]
It works:), thanks
