### ISSUE TITLE
Problem with edges points position when updated a form

### ISSUE THREAD

**Issue by rosaliaam0408** [iVis-at-Bilkent/cytoscape.js-edge-editing#25]
When updated a form the edges points move a little.

The edges points position is normal
![Captura de pantalla 2019-10-02 a la(s) 11 56 34](https://user-images.githubusercontent.com/43282793/66064808-c2604200-e50b-11e9-9ec0-8c69a84a6b82.png)

After updating the form
![Captura de pantalla 2019-10-02 a la(s) 11 56 42](https://user-images.githubusercontent.com/43282793/66064822-cab87d00-e50b-11e9-8101-cb569191dd10.png)

I have verified edge positions, zoom, pan and all the information that nodes and edges have before updating the form and after and they seem to match.

Thank you

#cytoscape

**Comment by ugurdogrusoz** [comment]
@rosaliaam0408 This extension is for manipulating (add/remove/move) edge bend points. It's activated when a single edge is selected. In your description, I don't see the extension in action. So I think you should open this issue in Cytoscape.js repository.
