### ISSUE TITLE
Undo-redo bug on the edge with bend point

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/cytoscape.js-edge-editing#28]
Actually, selection shouldn't be included in the undo-redo operations. If an element is selected it should continue as selected or vice versa. Currently, when we apply undo-redo operation, the edge with the bend point changes its selection state and if it's in selected state, reconnection handle may not drawn to the correct position. A sample can be seen below: ![Peek 2019-10-10 16-08](https://user-images.githubusercontent.com/22586369/66571969-d5f95180-eb78-11e9-8b01-1333c1e321fa.gif)

**Comment by ugurdogrusoz** [comment]
Let's discuss how we can avoid this as this was to cover another bug.

**Comment by nasimsaleh** [comment]
@hasanbalci I changed Undo Redo extension to unselect on drag. To see the changes in edge editing we have to merge unstable branch to master branch in undo redo, because it is being referenced in the index file of edge editing demo.

**Comment by ugurdogrusoz** [comment]
@nasimsaleh 
- This fix is not a workaround right? We don't first show the edge selected and then unselect it on undo?
- Assuming this fix was done on the unstable branch of this extension, why don't make the unstable branch use the unstable branch of the undo-redo extension to get the latest (the fix made for this issue)?

**Comment by nasimsaleh** [comment]
@ugurdogrusoz  It is not a work around, It doesn't get selected and then unselected. I will change the index file of unstable branch of edge editing to use unstable undo redo branch.

**Comment by ugurdogrusoz** [comment]
@hasanbalci Pls test and close if OK

**Comment by hasanbalci** [comment]
@nasimsaleh The bug is fixed but now when we keep a reconnection handle and drag, edge stays selected and both bend points and reconnection handles don't follow the edge. Before edge was unselected during this operation.

**Comment by ugurdogrusoz** [comment]
When compared to the public Newt (release 2.0.0), this version now keeps edge selected when we're reconnecting it. If the edge has a bend point(s), it displays the bend point(s) and reconnection handles in incorrect locations (no update). If the edge doesn't have any bend points, we don't display reconnection handles either (inconsistent).

**Comment by ugurdogrusoz** [comment]
Another problem is when you create a bend point by dragging. During drag the edge gets unselected (undesired behavior).

**Comment by ugurdogrusoz** [comment]
In line with our discussion, let's have this behavior consistently for both reconnecting an edge and editing its bends: When the operation starts, unselect the edge and select it back when finished. This includes edge context menu operations for adding and removing bends.
