### ISSUE TITLE
Cytoscape position event slows down the layouts

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/cytoscape.js-edge-editing#29]
Cytoscape position event on nodes (defined [here](https://github.com/iVis-at-Bilkent/cytoscape.js-edge-editing/blob/a75d8d3264553f1dda14f577b661db15414f0da3/src/UIUtilities.js#L534)) slows down the layouts, because it's triggered for each node at the end of the layout. For example, for a graph with 4500 nodes it may cause 7-8 seconds slowdown. It's actual purpose is to redraw bend points and reconnection handles if source or target node of the selected edge changes its position. However, it's triggered unnecessarily in many cases including layouts. Other similar events should also be evaluated for the same reason, but main slowdown is caused by position event in layouts.

**Comment by ugurdogrusoz** [comment]
@nasimsaleh Let's talk about how we can fix this.

**Comment by ugurdogrusoz** [comment]
@nasimsaleh Let's do this as follows:
Rather than listening to position change of nodes, let's listen to node drag event and when a node is being dragged:
1) deselect all edges (one or more)
2) deselect all nodes if the dragged node is *not* selected

**Comment by ugurdogrusoz** [comment]
Looks good to me from edge editing point of view.
@hasanbalci Pls check that this eliminates slow down of layout.

**Comment by hasanbalci** [comment]
@ugurdogrusoz Yes, this eliminates the slow down in the layout.
@nasimsaleh I added a comment to your commit, please make the desired changes.
