### ISSUE TITLE
$ is not defined

### ISSUE THREAD

**Issue by nikhilkharbas** [iVis-at-Bilkent/cytoscape.js-edge-editing#31]
Hi,I use react application with cytoscape..I try to use cytoscape-edge-editing plugin in my react application..I includes dependency like -
import cytoscape from 'cytoscape';
import $ from 'jquery';
import edgeEditing from 'cytoscape-edge-editing';
cytoscape.use(edgeEditing,jquery);

and call the api of  edge-editing like-
cy.edgeEditing(options);//options are defined

then I run my application get  error "$ is not defined" in node-module/cytoscape-edge-editing

**Comment by ugurdogrusoz** [comment]
Looks like this is duplicate with #32.
