### ISSUE TITLE
$ is not defined

### ISSUE THREAD

**Issue by nikhilkharbas** [iVis-at-Bilkent/cytoscape.js-edge-editing#32]
Hi,I use react application with cytoscape..I try to use cytoscape-edge-editing plugin in my react application..I includes dependency like -
import cytoscape from 'cytoscape';
import $ from 'jquery';
import edgeEditing from 'cytoscape-edge-editing';
cytoscape.use(edgeEditing,$);

and call the api of  edge-editing like-
cy.edgeEditing(options);//options are defined

then I run my application get  error "$ is not defined" in node-module/cytoscape-edge-editing

**Comment by nasimsaleh** [comment]
Hi @nikhilkharbas  I think it is an issue specific to your project modules management. It might be related to how React uses modules. I found [this](https://stackoverflow.com/questions/60197883/react-project-fails-to-use-node-modules-in-a-git-submodule) which is similar to yours. I would like to be more helpful but I don't have experience with React applications

**Comment by Hoogkamer** [comment]
For someone who experiences this in Nuxt view, I solved it by changing nuxt.config.js as follows:
- At the top add: const webpack = require('webpack')
- in the build configuration add:
-  build: {
    /*
     ** You can extend webpack config here
     */
    vendor: ['jquery'],
    plugins: [
      new webpack.ProvidePlugin({
        $: 'jquery'
      })
    ],

**Comment by ugurdogrusoz** [comment]
Thanks @Hoogkamer
