### ISSUE TITLE
Improve and add new item in context menu

### ISSUE THREAD

**Issue by VRatsim** [iVis-at-Bilkent/cytoscape.js-edge-editing#33]
Hello, I need on my project to add other display conditions for the context menu.
When there is no bend point on the line, only one item in the menu (add Bend Point)

If there is at least one bend point on the line, three items in the menu (add bend point + remove bend point+ remove all bend point)

Do you think added other option for the context menu? or do you have any suggestions to solve my problem?

**Comment by ugurdogrusoz** [comment]
@msalihaltun Could this be achieved with the current extension (as is)?

**Comment by msalihaltun** [comment]
#39 introduces the option to remove all bend points on an edge, provided there are more than one. This option is possible via adding a new class to edges only. Also works with undo-redo. But to be able to select when there is one and only one bend point on an edge requires the design of the extension to change and be able to work with number of bend points on an edge at any point, from what I understand. 

Single bend points can still be removed via the context menu on themselves, of course.

**Comment by hasanbalci** [comment]
Before merging #39 and solving this issue, let's wait the merge of #37, because it will require changes in #39.

**Comment by msalihaltun** [comment]
#37 has been merged, and multiple bend/control point removal is now possible on the new release of this extension.
