### ISSUE TITLE
Optional use of trailing dividers in context menus

### ISSUE THREAD

**Issue by msalihaltun** [iVis-at-Bilkent/cytoscape.js-edge-editing#42]
Currently, this extension doesn't use trailing dividers in its context menu item options by default and the extension options don't support changing this setting. This causes a problem when the extension is used in other applications that might also be creating context menu items of their own with trailing dividers: It will make their menu styles inconsistent with some items having trailing dividers and some not, with no way to control the setting for menu items related to this extension. 

To solve this issue, this extension should support enabling trailing dividers for context menu items of its own. This could be made optional and set to false by default for backward style compatibility.

**Comment by msalihaltun** [comment]
@hasanbalci can you please check that it works correctly?

**Comment by hasanbalci** [comment]
@msalihaltun It seems that it works correctly. The only problem may occur if the user adds edge-editing menu items last, since it will create a divider at the end of the menu, but I think it's not so important.  One thing I noticed with the commit is that `enableMultipleAnchorRemovalOption` option is added to README for the second time.

**Comment by msalihaltun** [comment]
The README is an oversight on my part, I will fix it. 

I think, maybe context menus extension should handle not putting trailing divider on the very last item, it doesn't make much sense anyway. It even puts trailing divider for a single item when enabled. What do you think @ugurdogrusoz @hasanbalci?

**Comment by ugurdogrusoz** [comment]
> I think, maybe context menus extension should handle not putting trailing divider on the very last item, it doesn't make much sense anyway. It even puts trailing divider for a single item when enabled. What do you think @ugurdogrusoz @hasanbalci?

Sure, makes sense.

**Comment by msalihaltun** [comment]
Related issue is https://github.com/iVis-at-Bilkent/cytoscape.js-context-menus/issues/56. Closing this now.
