### ISSUE TITLE
Endpoints not being deleted

### ISSUE THREAD

**Issue by gledis69** [iVis-at-Bilkent/cytoscape.js-edge-editing#43]
I was going through the project again and noticed this:
![newBugOnMaster](https://user-images.githubusercontent.com/43916939/93198415-acb44e80-f755-11ea-9a15-eda73fde67b1.gif)
The endpoints of edges are not being deleted. I checked and had the same issue in my local repo as well, which suggest that the changes made to the project did not cause this.
After some debugging I noticed this:
![KanvasNotWorking](https://user-images.githubusercontent.com/43916939/93198657-00bf3300-f756-11ea-98a9-08d71e3273a2.gif)
The calls to 
`endpoint1.destroy()
endpoint2.destroy()
canvas.draw()`
should clean the shapes from the stage, but the shapes aren't being removed.

On another note, Hasan noticed that the code is working fine in Newt.

**Comment by msalihaltun** [comment]
Seems solved now. Thanks @gledis69.

**Comment by hasanbalci** [comment]
It's ok now.
