### ISSUE TITLE
The screen doesn't update on the last undo of a "changeAnchorPoints" action

### ISSUE THREAD

**Issue by gledis69** [iVis-at-Bilkent/cytoscape.js-edge-editing#44]
![ScreenDoesntRefresh](https://user-images.githubusercontent.com/43916939/93206926-dcb61e80-f762-11ea-9c68-358216feadec.gif)

After I move the edge around twice and then try to undo, only one undo seems to be complete. The other undo also completes, but it is not shown on screen. When I zoom out/in it triggers a screen refresh and the change shows. 
This only appears to haven when causing actions which are stored as "changeAnchorPoints" and not with changing of edge endpoints.

Also Hasan checked and noticed this bug is not showing up in Newt.

**Comment by msalihaltun** [comment]
Seems solved.

**Comment by msalihaltun** [comment]
@gledis69 Just ran into another problem. When I remove all anchors and then undo, the style doesn't update. It uses the same 
`changeAnchorPoints` undo/redo action as the others.

**Comment by msalihaltun** [comment]
@hasanbalci @gledis69 please check in the demo that everything works now. Thank you.

**Comment by gledis69** [comment]
@msalihaltun Good catch, I didn't expect selected edges to have the issue as well.

**Comment by hasanbalci** [comment]
I think, it's working now.
