### ISSUE TITLE
Graph import/export problem, cy.json() is not working

### ISSUE THREAD

**Issue by limexp** [iVis-at-Bilkent/cytoscape.js-edge-editing#45]
Impossible to export and import graph at a later point of time with standard function [cy.json()](https://js.cytoscape.org/#cy.json).

The produced by cy.json() object is incorrect due to ```"selector": ".edgebendediting-hasbendpoints"``` and ```"selector": ".edgecontrolediting-hascontrolpoints"``` styles. Removing these styles makes it possible to load a graph, but without blend and control points.

### Steps to reproduce:
1. Open demo page https://ivis-at-bilkent.github.io/cytoscape.js-edge-editing/demo.html
2. Run from console: ```cy.json( cy.json() )```
3. The result:
```
The style property `segment-distances: fn` is invalid cytoscape.min.js:23:12071
Uncaught TypeError: M is null
    parseImpl https://unpkg.com/cytoscape/dist/cytoscape.min.js:32
    parseImplWarn https://unpkg.com/cytoscape/dist/cytoscape.min.js:32
    parse https://unpkg.com/cytoscape/dist/cytoscape.min.js:32
    cssRule https://unpkg.com/cytoscape/dist/cytoscape.min.js:32
    css https://unpkg.com/cytoscape/dist/cytoscape.min.js:32
    appendFromJson https://unpkg.com/cytoscape/dist/cytoscape.min.js:32
    fromJson https://unpkg.com/cytoscape/dist/cytoscape.min.js:32
    fromJson https://unpkg.com/cytoscape/dist/cytoscape.min.js:32
    setStyle https://unpkg.com/cytoscape/dist/cytoscape.min.js:32
    style https://unpkg.com/cytoscape/dist/cytoscape.min.js:32
    json https://unpkg.com/cytoscape/dist/cytoscape.min.js:32
    <anonymous> debugger eval code:1
debugger eval code:32:48009
```

Is there a quick workaround?

**Comment by msalihaltun** [comment]
Cytoscape.js documentation states the [following](https://js.cytoscape.org/#style/format): `If using functions as style values, it will not be possible to serialise and deserialise your stylesheet to JSON proper.` 

We use functions to style the elements in this extension, so you can't use `cy.json()` to serialise your graph.

For some possible workarounds, check [this](https://github.com/cytoscape/cytoscape.js/issues/2516)] issue.

**Comment by rkdover** [comment]
I have tried to work around this issue by loading a graph with `cy.remove()` and `cy.add()` after which I call `cy.edgeEditing()`, and while I do see the anchor points on selected edges (and can move them around) they do not attach to any nodes, instead snapping back to the original state. Is there something under the hood I'm missing?

**Comment by canbax** [comment]
@rkdover any updates on this? Maybe instead of `json` method you can simply keep a reference to current graph elements and graph styles. For example you can try `const elems = cy.json().elements;` to keep reference to graph elements and `const styles = cy.style()` to keep a reference to styles

**Comment by rkdover** [comment]
@canbax it was a while ago since I worked on this but I use the following code to load/save. I have to admit that I don't really understand cytoscape under the hood so I am hardly the right person to work on this...

Saving: (apparently just dropping the styles)
```
function saveFile() {
    const json = cy.json();
    download(JSON.stringify(json.elements), "network", "application/json")
}
```

Loading:
```
function initCy(data) {
    cy.remove(cy.elements())
    cy.add(data)

    cy.layout(layoutOptions).run();

    [...]
}

initCy(JSON.parse(data))
```

**Comment by canbax** [comment]
Your codes aren't doing anything style related. I think we can close this issue or add save/load methods to be used.

**Comment by canbax** [comment]
I don't think it count as "breaking built-in functionality". Using functions in styles can be necessary in some cases. Also, ˋcy.json()ˋ still works.

**Comment by canbax** [comment]
@rkdover I just see that we can replace functions with [mappers](https://js.cytoscape.org/#style/mappers). `cy.json(cy.json())` should work now.

**Comment by rkdover** [comment]
Awesome! Thank you for your work!

**Comment by hasanbalci** [comment]
Seems ok, so I'm closing.

**Comment by karchjd** [comment]
I am struggeling with this issue at the moment. `cy.json(cy.json())` does not seem to work. When running it on the demo, I get:

```
cytoscape.min.js:32 Uncaught TypeError: Cannot read properties of null (reading 'value')
    at Bs.parseImpl (cytoscape.min.js:32:51017)
    at e.parseImplWarn (cytoscape.min.js:32:49268)
    at e.parse (cytoscape.min.js:32:49145)
    at zs.cssRule (cytoscape.min.js:32:54125)
    at zs.css (cytoscape.min.js:32:54041)
    at e.appendFromJson (cytoscape.min.js:32:23623)
    at e.fromJson (cytoscape.min.js:32:23701)
    at Ns.fromJson (cytoscape.min.js:32:54579)
    at Os.setStyle (cytoscape.min.js:32:55062)
    at Os.style (cytoscape.min.js:32:54914)
```
