### ISSUE TITLE
getAnchorsAsArray: how to know if it is bend or control

### ISSUE THREAD

**Issue by Hoogkamer** [iVis-at-Bilkent/cytoscape.js-edge-editing#46]
Hi, thanks for this amazing stuff!

My question is, how to know if the getAnchorsAsArray returns bend points or control points. I now use the class of the edge to derive this, but this does not look like a solid solution to me.

var bendPoints = edgeEdit.getAnchorsAsArray(n)
 if (n.classes().includes('edgebendediting-hasbendpoints')) {
        bendType = 'bend'
      } else if (
        n.classes().includes('edgecontrolediting-hascontrolpoints')
      ) {
        bendType = 'control'
      }

**Comment by msalihaltun** [comment]
Hello @Hoogkamer, thanks for your interest.

There is an internal function [here](https://github.com/iVis-at-Bilkent/cytoscape.js-edge-editing/blob/149c0aa59b0f5d2a39a3150b81f85f0f01105333/src/anchorPointUtilities.js#L34) that uses class and data information to determine edge type as one of `bend`, `control` or `inconclusive`. 

We could expose this function as a part of the extension API, but your solution should work quite well as well.

Should we expose a function explicitly for this purpose @ugurdogrusoz?

**Comment by ugurdogrusoz** [comment]
@msalihaltun Yes, it would be nice to expose the type of an edge. Takes an edge and returns the type of its anchor points (bend, control, none?).

**Comment by msalihaltun** [comment]
`instance.getEdgeType()` with return type `'bend'` `'control'` or `'none'` is exposed now in unstable branch. 

Thank you @Hoogkamer, this should be part of the next release.

**Comment by msalihaltun** [comment]
@hasanbalci I also made some internal API changes with [this commit](https://github.com/iVis-at-Bilkent/cytoscape.js-edge-editing/commit/531549e44a4ba2157ff4a8079b81c0d6a618dbb7). It is just renaming / refactoring work, and it seemed fine to me in testing, but can you also test it to make sure?

**Comment by Hoogkamer** [comment]
@msalihaltun Thank you very much!

**Comment by hasanbalci** [comment]
@msalihaltun It seems working well, thanks!
