### ISSUE TITLE
Expose functions used in context menu

### ISSUE THREAD

**Issue by Hoogkamer** [iVis-at-Bilkent/cytoscape.js-edge-editing#47]
Thanks for your help earlier!

For me it would also be handy do have the functions exposed you use in your menu.
I currently use my own menu, and it would be much more flexible if I can create my own menu items so I have more control over these items.

https://github.com/iVis-at-Bilkent/cytoscape.js-edge-editing/blob/149c0aa59b0f5d2a39a3150b81f85f0f01105333/src/UIUtilities.js#L339-L378

**Comment by msalihaltun** [comment]
Hello again.

I don't think it is a good idea for us to expose these functions actually. They use the position of the mouse on the edge (on right click) to figure out where to put the anchor point. They would function fine just as long as people use them for the exact same purpose, but there is no general `addAnchorAtPosition` function (or something similar). The extension was designed to work around context menu events, there is currently no functionality to add anchor points programatically.

Maybe we can think of another way to give users more control over the menu items.

**Comment by Hoogkamer** [comment]
Thank you, I understand.

Maybe it is then possible to detect if the is a menu item with  id: removeAllControlPointCtxMenuId for example.
And then leave the rest as is, but only add the onClickFunction: cxtRemoveAllAnchorsFcn 

But if I am the only one requesting this, I could also have a look if I could do something like that. So change the menu after the items have been added by the edge-editing initialization.

**Comment by canbax** [comment]
Hi @Hoogkamer It's been time. Do you still need this functionality? 

Maybe we can add more options to API. For example, maybe you can pass your own functions and we can call those functions. Does it work? Also, do you need any parameters in those functions?

**Comment by Hoogkamer** [comment]
Hi @canbax, reading my issue back, is maybe not really describing it completely clear. Currently, the extension does itself append the options to the context menu. But I would like to place it somewhere in the middle, not at the end. For example, I would like to have "Delete"  (the relation) at the end in my menu. 
![image](https://user-images.githubusercontent.com/17671871/140536905-c109787d-3aea-4e3a-a58f-333f879be99b.png)

**Comment by canbax** [comment]
I see. For now, you can try removing the item and then adding again with [context menu API](https://github.com/iVis-at-Bilkent/cytoscape.js-context-menus#instanceremovemenuitemitemid). In this way, delete would be the last one I guess. 

We might add another API method to the context menu to switch the order of items. This is totally related to the context menu.

**Comment by Hoogkamer** [comment]
Ok, thank you for the tip!

**Comment by hasanbalci** [comment]
A workaround similar to what @canbax suggests is first appending the menu items that you want before edge-editing related items, then initializing the edge-editing extension and finally appending the rest of the menu items:

```
let contextMenus = cy.contextMenus( ... );

contextMenus.appendMenuItems( initialItems ) // initialItems are the ones you want before edge-editing related ones.

cy.edgeEditing( options ); // this will append edge-editing related menu items

contextMenus.appendMenuItems( endItems ) // endItems are the ones you want after edge-editing related ones.
```

**Comment by canbax** [comment]
maybe we can add a function in context menu API to switch the places of menu items or change the order of menu items.

**Comment by canbax** [comment]
@Hoogkamer New API method into [context-menus extension](https://github.com/iVis-at-Bilkent/cytoscape.js-context-menus/commit/6626dcf2a5738a84979ebaeeb1dc3527e9955fbf) is added. You can use that function in the unstable branch of the context menu extension.
