### ISSUE TITLE
Enabled option does not function as expected

### ISSUE THREAD

**Issue by msalihaltun** [iVis-at-Bilkent/cytoscape.js-edge-editing#49]
The `enabled` option starts the extension in enabled/non-enabled way as expected, but there is no way to dynamically enable/disable it again, which means the user might as well have not used the extension anyways if they are disabling edge-editing this way. 

An argument could be made where different instances of an application may want to enable-disable edge editing at initialization based on the instance, but then the API functions and menu options don't respect enabled/disabled state and return errors since only the `options` object is affected by `enabled`. Then the application using API functions needs to check whether the extension was enabled in the first place anyways, which means the option is useless.

Thus we should either remove this option, or change it to function as expected and not return errors when disabled, maybe even add `enable()` and `disable()` functions to the API. I'm not sure how these functions would operate seamlessly with an application in a dynamic way though (as in while the application is working, would anchors just disappear when disabled?).

**Comment by msalihaltun** [comment]
@ugurdogrusoz how do you think we should proceed with this?

**Comment by ugurdogrusoz** [comment]
Normally, enabling/disabling this extension wouldn't create complications as you described. Control/bend points exist in Cytoscape.js core and could live without this extension just fine.
Let's see if enable/disable ever worked dynamically. If so, let's restore it. Otherwise, let's just get rid of it completely.

**Comment by msalihaltun** [comment]
It appears we never used `enabled` in a dynamic way. We should just remove it. Instead of initializing the extension in disabled state, applications should prefer not to initialize it when they don't need to.
