### ISSUE TITLE
Cytoscape warning on edge reconnection

### ISSUE THREAD

**Issue by msalihaltun** [iVis-at-Bilkent/cytoscape.js-edge-editing#50]
We create a temporary dummy edge while doing edge disconnection/reconnection. Apparently this edge sets style properties on element creation, which is deprecated and a warning is shown in console.

This is not very important, but we should probably adjust to the standards of cytoscape as they change.

**Comment by msalihaltun** [comment]
@hasanbalci can you confirm that this is fixed on unstable demo?

**Comment by hasanbalci** [comment]
Yes, it's fixed. Thanks!

**Comment by msalihaltun** [comment]
Reopening for now in light of https://github.com/iVis-at-Bilkent/newt/issues/652.

**Comment by msalihaltun** [comment]
I made a mistake with the styles, should be ok now. Can you confirm again @hasanbalci?
