### ISSUE TITLE
Disable reconnect an edge

### ISSUE THREAD

**Issue by dmal225** [iVis-at-Bilkent/cytoscape.js-edge-editing#51]
Is it possible to disable (remove) reconnection controls?
![image](https://user-images.githubusercontent.com/26773774/108168244-06a3b080-7108-11eb-8c42-773777a781ae.png)

**Comment by ugurdogrusoz** [comment]
Actually, we should allow the user to disable both reconnection controls and bend/control points (independently)

**Comment by truefusion** [comment]
Would like to see reconnect controls disabled by passing boolean false to handleReconnectEdge option, and enabled if given a function. I currently have an empty function to prevent reconnects. The residue left behind by the reconnect controls is undesirable.

**Comment by hasanbalci** [comment]
I'm closing this issue for the sake of #62. #62 aims to make both anchor points and reconnection handles optional.
