### ISSUE TITLE
bug: create unwanted bendpoint

### ISSUE THREAD

**Issue by leolumicrosoft** [iVis-at-Bilkent/cytoscape.js-edge-editing#53]
Hi,

the bug can be reproduced using your demo webpage https://ivis-at-bilkent.github.io/cytoscape.js-edge-editing/demo.html

choose menu to create a bendpoint in an edge, then follow up immediately to drag the point to some where, it may cause two bendpoints adding to the same location and only one of them is dragged away.

it may also happen after a bendpoint is created, just drag it to somewhere then quickly drag it again to another place, sometimes it will create also an unwanted additional bendpoint in its original position.
![image](https://user-images.githubusercontent.com/68049677/117924901-13abf680-b329-11eb-8030-d47b087a5924.png)

**Comment by ugurdogrusoz** [comment]
@leolumicrosoft I am guessing that you're not hitting the bend point but a point near the bend point, hence creating a new one each time. Zoom in a bit and try again, please. Perhaps we could provide a sensitivity option (similar to what we have for the removal of bends) or generalize the existing one in the future to eliminate such cases.

**Comment by leolumicrosoft** [comment]
Thank you for the answer, two questions I have
1. is it an expected behavior that dragging near bend point to create a new bend point? If yes, why shall we have another way besides context menu to create bend point?
2.  Is it possible to draw the bend point and control point dot bigger? or even better, dynamically enlarge it when I zoom out. I notice when I zoom out, the bend or control point dot is also shrinked.

**Comment by ugurdogrusoz** [comment]
1. Yes, we provide this (starting a drag on the edge to create a new bend point) for convenience. Please see the animated gif in the extension readme.
2. anchorShapeSizeFactor controls the size of the anchor (bend/control) points.

**Comment by leolumicrosoft** [comment]
Thank you for your quick response, it is direct to the point.
One more ask for point 1 before closing this thread, is it possible to disable this capability (creating bendpoint by dragging existed bend point edge)?

**Comment by leolumicrosoft** [comment]
can I pull request to this project? I test a change in code to make this createanchorondrag optional.
In index.js, add an option 
// whether allows adding bending point by draging edge without useing ctxmenu, default is true
      enableCreateAnchorOnDrag:true

in UIUtilities,js, line 978
if(createAnchorOnDrag && **opts.enableCreateAnchorOnDrag** && !anchorTouched && type !== 'inconclusive') {

**Comment by ugurdogrusoz** [comment]
Please make any pull requests to the unstable branch
