### ISSUE TITLE
Anchors and endpoints stay rendered when a group of elements with a single edge is selected

### ISSUE THREAD

**Issue by msalihaltun** [iVis-at-Bilkent/cytoscape.js-edge-editing#58]
The extension only checks for selected edges and that the edge is the only selected one. It doesn't consider nodes can be selected. Which leads to weird behavior like selecting an edge and selecting a node afterwards leaving edge anchors and endpoints rendered still.

First came to attention [here](https://github.com/iVis-at-Bilkent/pathway-mapper/issues/216).

**Comment by ugurdogrusoz** [comment]
This is by design actually. To avoid rendering issues, we had decided to display anchors and reconnection handles only when a single edge is selected independent of the number of nodes selected.
