### ISSUE TITLE
Error while undoing of single anchor point creation on selected edge

### ISSUE THREAD

**Issue by msalihaltun** [iVis-at-Bilkent/cytoscape.js-edge-editing#59]
- Create a single anchor on any edge in the demo.
- Select the edge so anchor point and endpoints are drawn.
- Ctrl + Z. See the error in the console.

**Comment by msalihaltun** [comment]
@hasanbalci can you confirm that this works? Thanks.

Also this extension has a lot of workarounds to render styles (select-unselect etc). We should go over them at some point.

**Comment by hasanbalci** [comment]
It seems working. Thanks!
