### ISSUE TITLE
Catching the existence of optional dependencies

### ISSUE THREAD

**Issue by rkdover** [iVis-at-Bilkent/cytoscape.js-edge-editing#61]
Would be nice if an event listener for "cxttap" wasn't bound if context menu is not included, as this makes it throw errors. Would also appreciate it if anyone has a workaround for now

**Comment by canbax** [comment]
@rkdover it should be fixed now.

**Comment by ugurdogrusoz** [comment]
@hasanbalci Pls check and close if ok
