### ISSUE TITLE
Remove jquery dependency

### ISSUE THREAD

**Issue by arthabus** [iVis-at-Bilkent/cytoscape.js-edge-editing#64]
Hi, is there an easy way to remove the jquery dependency? Need this lib but it's a requirement for the project I'm part of to not include jquery

**Comment by canbax** [comment]
Hi @arthabus we just made a new commit in the unstable branch. You shouldn't need jquery anymore. Let me know if there are any issues.

**Comment by hasanbalci** [comment]
This seems ok now, so I'm closing.
