### ISSUE TITLE
Right-click does not open context menu sometimes

### ISSUE THREAD

**Issue by canbax** [iVis-at-Bilkent/cytoscape.js-edge-editing#66]
1. Right-click to an edge (nothing will happen, it is expected)
2. Left-click to the edge to select it.
3. Right-click again to the edge to open context-menu items on the edge.
You will see that the context menu is still not opened. You can see this in the below video.

https://user-images.githubusercontent.com/8426741/139662505-c7d9fea9-e1a6-4449-8b00-0895f373fe45.mp4

The reason for this bug lies in the context menu extension. When we show or hide a menu item, sometimes we hide all the items. After that we show a menu item, the parent DOM element stays invisible (`display: 'none'`).

The reverse also happens. We hide all the menu items but the parent stays visible. In this case, we see a dot-like shape in the empty canvas. You can observe this case in the below image.
![image](https://user-images.githubusercontent.com/8426741/139663586-0dd22e5b-bee8-490e-8b04-1a8737683cf3.png)

**Comment by ugurdogrusoz** [comment]
@canbax I tried doing this with the demo on master branch and it worked fine?

**Comment by canbax** [comment]
I did observe the same things on the demo on master as well. The right-click issue is a bit weird. But dot-like shape happens consistently when you first open the demo.

**Comment by hasanbalci** [comment]
This seems to be fixed now with the commit in context-menus extension, it will be available when context-menus extension is released.
