### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by arthabus** [iVis-at-Bilkent/cytoscape.js-edge-editing#68]
Remove jQuery dependency

**Comment by canbax** [comment]
this is done in the [unstable branch](https://github.com/iVis-at-Bilkent/cytoscape.js-edge-editing/tree/unstable)

**Comment by arthabus** [comment]
Thanks for the update. Do you plan to merge it to master?

On a separate note, are there any plans/technical possibility to remove Konva as well?

**Comment by hasanbalci** [comment]
We merge unstable branch to master before a new release, but we cannot give a specific date for the next release for now.

There is currently no plan to remove Konva dependency, at least in the short term.
