### ISSUE TITLE
Load Using Import

### ISSUE THREAD

**Issue by karchjd** [iVis-at-Bilkent/cytoscape.js-edge-editing#71]
Thanks a lot for your great packages! 

I am using vite and, as a consequence, cannot use require, only import. Could you please advice me on how to load your module in such an environment? For your other gridguides module, simply replacing require with import worked. But this did not work for this package.

Thanks a lot for your help!

**Comment by hasanbalci** [comment]
Did you try this:
```
import cytoscape from 'cytoscape';
import $ from 'jquery';
import Konva from 'konva';
import nodeEditing from 'cytoscape-edge-editing';
nodeEditing(cytoscape, $, Konva);
```

**Comment by karchjd** [comment]
Thanks that solved the issue!

Am Mi., 5. Juli 2023 um 22:27 Uhr schrieb Hasan Balcı <
***@***.***>:
