### ISSUE TITLE
add option for round segments

### ISSUE THREAD

**Issue by Hoogkamer** [iVis-at-Bilkent/cytoscape.js-edge-editing#74]
Hi, great package. 
Is it possible to add a menu option to select round segments instead of the standard segments only?

https://js.cytoscape.org/#style/round-segments-edges

**Comment by ugurdogrusoz** [comment]
@Hoogkamer we do not have any resources to work on new features. Feel free to create a PR (to the **unstable** branch please) for it if straightforward.

**Comment by hasanbalci** [comment]
@Hoogkamer Thanks for the PR #76. I merged it and the new feature will be available with the next release.
